### ISSUE TITLE
omg, how to use?

### ISSUE THREAD

**Issue by Suburbanno** [lawloretienne/SoundCloud#2]

**Comment by lawloretienne** [comment]
@Suburbanno can you provide some more info?

**Comment by Suburbanno** [comment]
How can I use? I mean, is there any APK?

**Comment by lawloretienne** [comment]
I will need to add an APK once i upload it to a release.

**Comment by Suburbanno** [comment]
Okay, waiting!

**Comment by lawloretienne** [comment]
@Suburbanno I published an APK in <a href="https://github.com/lawloretienne/SoundCloud/releases">Releases</a>

**Comment by Suburbanno** [comment]
Many thanks, great job!
